steps:
  # Step 1: Build the WebSocket server image from the root Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build WebSocket Server'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextads-socket-server:$COMMIT_SHA', '.']

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push WebSocket Server'
    args: ['push', 'gcr.io/$PROJECT_ID/nextads-socket-server:$COMMIT_SHA']

  # Step 3: Deploy the new image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy WebSocket Server'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nextads-socket-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nextads-socket-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--port'
      - '8080'
    waitFor: ['Push WebSocket Server']

  # Step 4: Set the IAM policy to allow public (unauthenticated) access
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'nextads-socket-server'
      - '--region'
      - 'us-central1'
      - '--member=allUsers'
      - '--role=roles/run.invoker'
    waitFor: ['Deploy WebSocket Server']
