steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'nextads-server'
    - '--source'
    - '.'
    - '--region'
    - 'asia-south1'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
